#ifndef _CONFIGURATION_H
#define _CONFIGURATION_H

//#define PARALLEL_INPUT_LOAD
#define PARTITIONED_INPUT_LOAD
//#define SEQUENTIAL_INPUT_LOAD

#define SORT_LARGEST_DEGREE_FIRST
//#define SORT_SMALLEST_DEGREE_FIRST
//#define SORT_VERTEX_ORDER
//#define SORT_VERTEX_ORDER_REVERSED

#define PARALLEL_GRAPH_COLOR
//#define SEQUENTIAL_GRAPH_COLOR

//#define PARALLEL_RECOLOR
#define SEQUENTIAL_RECOLOR

#define COMPUTE_ELAPSED_TIME

////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////

#ifdef PARALLEL_INPUT_LOAD
#undef PARTITIONED_INPUT_LOAD
#undef SEQUENTIAL_INPUT_LOAD
#endif

#ifdef PARTITIONED_INPUT_LOAD
#undef PARALLEL_INPUT_LOAD
#undef SEQUENTIAL_INPUT_LOAD
#endif

#ifdef SEQUENTIAL_INPUT_LOAD
#undef PARALLEL_INPUT_LOAD
#undef PARTITIONED_INPUT_LOAD
#endif

#ifdef SORT_LARGEST_DEGREE_FIRST
#undef SORT_SMALLEST_DEGREE_FIRST
#undef SORT_VERTEX_ORDER
#undef SORT_VERTEX_ORDER_REVERSED 
#endif

#ifdef SORT_SMALLEST_DEGREE_FIRST
#undef SORT_LARGEST_DEGREE_FIRST
#undef SORT_VERTEX_ORDER
#undef SORT_VERTEX_ORDER_REVERSED 
#endif

#ifdef SORT_VERTEX_ORDER
#undef SORT_LARGEST_DEGREE_FIRST
#undef SORT_SMALLEST_DEGREE_FIRST
#undef SORT_VERTEX_ORDER_REVERSED 
#endif

#ifdef SORT_VERTEX_ORDER_REVERSED 
#undef SORT_LARGEST_DEGREE_FIRST
#undef SORT_SMALLEST_DEGREE_FIRST
#undef SORT_VERTEX_ORDER
#endif

#ifdef PARALLEL_GRAPH_COLOR
#undef SEQUENTIAL_GRAPH_COLOR
#endif

#ifdef SEQUENTIAL_GRAPH_COLOR
#undef PARALLEL_GRAPH_COLOR
#endif

#ifdef PARALLEL_RECOLOR
#undef SEQUENTIAL_RECOLOR
#endif

#ifdef SEQUENTIAL_RECOLOR
#undef PARALLEL_RECOLOR
#endif

#endif // !_CONFIGURATION_H